version: "3.1"

language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: word
    stop_words: null
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 2
    max_ngram: 4
  - name: DIETClassifier
    epochs: 200  # Increased for more comprehensive training
    constrain_similarities: true  # Keep as True for cross-entropy loss
    random_seed: 42  # Ensures reproducibility
    entity_recognition: true  # Ensures better handling of entities
    batch_strategy: balanced
    use_masked_language_model: true  # Useful for better intent understanding
    learning_rate: 0.002  # Adjusted for better convergence
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 150  # Increased for better performance
    constrain_similarities: true  # Ensure better similarity handling
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

policies:
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: true
  - name: MemoizationPolicy
    max_history: 10  # Increase for more complex conversations
  - name: TEDPolicy
    max_history: 10  # Increase history for better contextual understanding
    epochs: 300  # More epochs for improved learning
    batch_size: [16, 64]  # Dynamic batching for better performance
    learning_rate: 0.002
    random_seed: 42  # Ensures reproducibility
    constrain_similarities: true

assistant_id: 20241205-210316-azure-combustion
